import { Check, CheckCircle2, ChevronLeft, ChevronRight, CircleOff, Coffee, History, Inbox, LoaderCircle, MessageCircle, Phone, Radio, RotateCcw, Search, Send, Trash2, UserRound, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { t, type Locale } from "../lib/i18n";
import { formatDuration } from "../lib/format";
import type { CitizenRequest, CompanyWorkspace as WorkspaceData, Employee, EmployeeStatus, InboxConversation, RequestSettings, WorkspaceCursor, WorkspaceSection } from "../types";

type WorkspaceTab = "requests" | "inbox" | "calls" | "team";
interface Props {
  data: WorkspaceData | null; employees: Employee[]; selfSource: number; locale: Locale; busy: boolean; employeeStatus?: EmployeeStatus; activeRequestId?: number;
  onOpenConversation: (conversation: InboxConversation) => void; onAcceptRequest: (request: CitizenRequest) => void;
  onTransition: (request: CitizenRequest, phaseId: string) => void; onReturn: (request: CitizenRequest) => void;
  onSaveSettings: (settings: Pick<RequestSettings, "label" | "createLabel" | "templateIds" | "fieldSettings" | "numberId" | "navigationOnAccept">) => void;
  onDeleteRequest: (request: CitizenRequest) => void; onDeleteConversation: (conversation: InboxConversation) => void;
  onCallEmployee: (employee: Employee) => void; onContactEmployee: (employee: Employee) => void;
  isLeader: boolean;
  canDelete: boolean;
  onLoadMore?: (section: WorkspaceSection, cursor?: WorkspaceCursor, conversationNumberId?: string) => Promise<boolean>;
  onInboxChange?: (numberId?: string) => Promise<boolean>;
  onCallsSeen?: (latestCallId: number) => void;
}

const pageSize = 8;
const pageSlice = <T,>(items: T[], page: number) => items.slice(page * pageSize, (page + 1) * pageSize);
const validPage = (page: number, total: number) => Math.min(page, Math.max(0, Math.ceil(total / pageSize) - 1));
const statusIcon = (status: EmployeeStatus) => status === "available" ? <CheckCircle2 size={14} /> : status === "on_break" ? <Coffee size={14} /> : status === "occupied" ? <CircleOff size={14} /> : <Radio size={14} />;
const statusPriority: Record<EmployeeStatus, number> = { available: 0, busy: 1, occupied: 2, on_break: 3, off_duty: 4 };
const getSeenCallId = (key: string) => { try { return Number(window.sessionStorage.getItem(key)) || 0; } catch { return 0; } };

export function CompanyWorkspace({ data, employees, selfSource, locale, busy, employeeStatus, activeRequestId, onOpenConversation, onLoadMore, onInboxChange, onCallsSeen, onAcceptRequest, onTransition, onReturn, onSaveSettings, onDeleteRequest, onDeleteConversation, onCallEmployee, onContactEmployee, isLeader, canDelete }: Props) {
  const [tab, setTab] = useState<WorkspaceTab>(() => { try { const saved = window.sessionStorage.getItem("services-plus-portal-tab"); return saved === "inbox" || saved === "calls" || saved === "team" ? saved : "requests"; } catch { return "requests"; } });
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [selectedInbox, setSelectedInbox] = useState<string>("all");
  const [teamQuery, setTeamQuery] = useState("");
  const [pages, setPages] = useState<Record<WorkspaceTab, number>>({ requests: 0, inbox: 0, calls: 0, team: 0 });
  const [loadingSection, setLoadingSection] = useState<WorkspaceSection | null>(null);
  const [seenCallIds, setSeenCallIds] = useState<Record<string, number>>({});
  const canAcceptRequests = employeeStatus === "available" && !activeRequestId;
  const filteredEmployees = useMemo(() => { const query = teamQuery.trim().toLocaleLowerCase(locale); return [...employees].filter((employee) => !query || `${employee.name} ${employee.role}`.toLocaleLowerCase(locale).includes(query)).sort((a, b) => Number(b.isLeader) - Number(a.isLeader) || (b.grade || 0) - (a.grade || 0) || statusPriority[a.status] - statusPriority[b.status] || a.name.localeCompare(b.name, locale)); }, [employees, locale, teamQuery]);
  const callSeenKey = data?.companyId ? `services-plus-seen-calls:${data.companyId}` : null;
  if (!data) return <section className="workspace loading"><LoaderCircle className="spinner" size={22} /></section>;
  const requests = data.requests;
  const conversations = data.conversations;
  const calls = data.calls;
  const unansweredRequests = data.summary?.unansweredRequests ?? data.requests.filter((request) => request.status === "pending" || request.status === "returned").length;
  const unreadMessages = data.summary?.unreadMessages ?? data.conversations.reduce((sum, item) => sum + Number(item.unreadCount || 0), 0);
  const seenCallId = callSeenKey ? seenCallIds[callSeenKey] ?? getSeenCallId(callSeenKey) : 0;
  const unseenCalls = tab === "calls" ? 0 : data.summary?.unseenCalls ?? data.calls.filter((call) => call.id > seenCallId).length;
  const requestPage = validPage(pages.requests, requests.length); const inboxPage = validPage(pages.inbox, conversations.length);
  const callsPage = validPage(pages.calls, calls.length); const teamPage = validPage(pages.team, filteredEmployees.length);
  const markCallsSeen = () => { if (!callSeenKey) return; const latest = data.summary?.latestCallId ?? (data.calls.length ? Math.max(...data.calls.map((call) => call.id)) : 0); if (!latest) return; setSeenCallIds((current) => current[callSeenKey] === latest ? current : { ...current, [callSeenKey]: latest }); try { window.sessionStorage.setItem(callSeenKey, String(latest)); } catch { /* Session persistence is optional. */ } onCallsSeen?.(latest); };
  const selectTab = (next: WorkspaceTab) => { if (next === "calls" || tab === "calls") markCallsSeen(); setTab(next); try { window.sessionStorage.setItem("services-plus-portal-tab", next); } catch { /* Session persistence is optional. */ } };
  const changePage = (target: WorkspaceTab, page: number) => setPages((current) => ({ ...current, [target]: page }));
  const loadNext = async (target: Exclude<WorkspaceTab, "team">, section: WorkspaceSection) => {
    if (!onLoadMore || loadingSection || !data.pagination[section].hasMore) return;
    setLoadingSection(section);
    const loaded = await onLoadMore(section, data.pagination[section].nextCursor, section === "conversations" && selectedInbox !== "all" ? selectedInbox : undefined);
    setLoadingSection(null);
    if (loaded) setPages((current) => ({ ...current, [target]: current[target] + 1 }));
  };
  return <section className="workspace"><div className="workspace-tabs"><button type="button" className={tab === "requests" ? "active" : ""} onClick={() => selectTab("requests")} title={t(locale, "requests")} aria-label={t(locale, "requests")}><Send size={17} /><i className={unansweredRequests > 0 ? "alert" : "neutral"}>{unansweredRequests}</i></button><button type="button" className={tab === "inbox" ? "active" : ""} onClick={() => selectTab("inbox")} title={t(locale, "inbox")} aria-label={t(locale, "inbox")}><Inbox size={17} /><i className={unreadMessages > 0 ? "alert" : "neutral"}>{unreadMessages}</i></button><button type="button" className={tab === "calls" ? "active" : ""} onClick={() => selectTab("calls")} title={t(locale, "companyCalls")} aria-label={t(locale, "companyCalls")}><History size={17} /><i className={unseenCalls > 0 ? "alert" : "neutral"}>{unseenCalls}</i></button><button type="button" className={tab === "team" ? "active" : ""} onClick={() => selectTab("team")} title={t(locale, "activeTeam")} aria-label={t(locale, "activeTeam")}><Users size={17} /><i className="neutral">{employees.length}</i></button></div>
    {tab === "requests" && <div className="workspace-list"><header><strong>{data.requestSettings.label}</strong>{isLeader && <button type="button" onClick={() => setSettingsOpen((value) => !value)}>{t(locale, "configure")}</button>}</header>{settingsOpen && <RequestSettingsEditor settings={data.requestSettings} locale={locale} busy={busy} onSave={(settings) => { onSaveSettings(settings); setSettingsOpen(false); }} />}{pageSlice(requests, requestPage).map((request) => {
      const own = request.id === activeRequestId;
      const phases = request.phases || data.requestSettings.phases;
      const current = phases.findIndex((phase) => phase.id === (request.phaseId || request.phase_id));
      const next = phases[current + 1];
      return <article className="work-row" key={request.id}><span className={`work-state ${request.status}`}><Send size={16} /></span><div><strong>{request.requestLabel || request.request_label || request.templateId || request.template_id}</strong><small>{request.companyName ? `${request.companyName} · ` : ""}{Object.values(request.payload || {}).filter(Boolean).slice(0, 2).join(" · ")}</small>{request.assignee && <small className="request-assignee"><UserRound size={13} />{t(locale, "assignedTo")}: {request.assignee.name || t(locale, "assignedEmployee")}{request.assignee.role ? ` · ${request.assignee.role}` : ""}</small>}<em>{request.status} · {request.phaseId || request.phase_id || t(locale, "waiting")}</em></div><span className="row-actions">{(request.status === "pending" || request.status === "returned") && <button type="button" disabled={busy || !canAcceptRequests} onClick={() => onAcceptRequest(request)} title={t(locale, "accept")}><Check size={16} /></button>}{own && next && <button type="button" disabled={busy} onClick={() => onTransition(request, next.id)} title={next.name}><ChevronRight size={17} /></button>}{own && <button type="button" disabled={busy} onClick={() => onReturn(request)} title={t(locale, "returnRequest")}><RotateCcw size={16} /></button>}{canDelete && request.companyId === data.companyId && <button type="button" className="danger" disabled={busy} onClick={() => onDeleteRequest(request)} title={t(locale, "deleteRequest")}><Trash2 size={16} /></button>}</span></article>;
    })}{!requests.length && <div className="workspace-empty">{t(locale, "noRequests")}</div>}<Pagination page={requestPage} total={requests.length} locale={locale} hasMore={data.pagination.requests.hasMore} loading={loadingSection === "requests"} onPage={(page) => changePage("requests", page)} onNext={() => void loadNext("requests", "requests")} /></div>}
    {tab === "inbox" && <div className="workspace-list"><div className="inbox-number-tabs"><button type="button" className={selectedInbox === "all" ? "active" : ""} onClick={() => { setSelectedInbox("all"); changePage("inbox", 0); void onInboxChange?.(); }}><Inbox size={15} />{t(locale, "allInboxes")}</button>{data.numberStates?.filter((number) => number.enabled && number.inboxEnabled).map((number) => { const unread = Number(data.summary?.unreadByNumber[number.numberId] || 0); return <button type="button" className={selectedInbox === number.numberId ? "active" : ""} key={number.numberId} onClick={() => { setSelectedInbox(number.numberId); changePage("inbox", 0); void onInboxChange?.(number.numberId); }}><Inbox size={15} />{number.label}<i className={unread > 0 ? "alert" : "neutral"}>{unread}</i></button>; })}</div>{pageSlice(conversations, inboxPage).map((conversation) => <article className="conversation-row" key={conversation.id}><button type="button" className="conversation-open" onClick={() => onOpenConversation(conversation)}><span><Inbox size={17} /></span><div><strong>{conversation.externalNumber}</strong><small>{conversation.numberLabel} · {conversation.lastMessage}</small></div>{Number(conversation.unreadCount) > 0 && <i>{conversation.unreadCount}</i>}</button>{canDelete && <button type="button" className="conversation-delete" disabled={busy} onClick={() => onDeleteConversation(conversation)} title={t(locale, "deleteConversation")}><Trash2 size={16} /></button>}</article>)}{!conversations.length && <div className="workspace-empty">{t(locale, "noMessages")}</div>}<Pagination page={inboxPage} total={conversations.length} locale={locale} hasMore={data.pagination.conversations.hasMore} loading={loadingSection === "conversations"} onPage={(page) => changePage("inbox", page)} onNext={() => void loadNext("inbox", "conversations")} /></div>}
    {tab === "calls" && <div className="workspace-list">{pageSlice(calls, callsPage).map((call) => { const queueDuration = formatDuration(call.queueDurationSeconds); const callDuration = formatDuration(call.callDurationSeconds); const distribution = call.distribution === "ring_all" ? t(locale, "ringAll") : call.distribution === "random" ? t(locale, "random") : call.distribution === "dispatch_only" ? t(locale, "dispatchOnly") : null; return <article className="work-row" key={call.id}><span className="work-state call"><Phone size={16} /></span><div><strong>{call.callerNumber || t(locale, "unknownCaller")}</strong><small>{call.numberId}{distribution ? ` · ${distribution}` : ""}</small><em>{call.status} · {new Date(call.created_at).toLocaleDateString(locale)}</em>{(queueDuration || callDuration) && <em className="call-duration">{queueDuration && `${t(locale, "queueDuration")}: ${queueDuration}`}{queueDuration && callDuration ? " · " : ""}{callDuration && `${t(locale, "callDuration")}: ${callDuration}`}</em>}</div></article>; })}{!calls.length && <div className="workspace-empty">{t(locale, "noCalls")}</div>}<Pagination page={callsPage} total={calls.length} locale={locale} hasMore={data.pagination.calls.hasMore} loading={loadingSection === "calls"} onPage={(page) => changePage("calls", page)} onNext={() => void loadNext("calls", "calls")} /></div>}
    {tab === "team" && <div className="workspace-list employee-section"><div className="team-toolbar"><Search size={15} /><input value={teamQuery} onChange={(event) => { setTeamQuery(event.target.value); changePage("team", 0); }} placeholder={t(locale, "teamSearch")} aria-label={t(locale, "teamSearch")} /></div><div className="employee-list">{pageSlice(filteredEmployees, teamPage).map((employee) => <div className="employee-row" key={employee.source}><span className={`avatar status-${employee.status}`}>{employee.name.slice(0, 1).toUpperCase()}</span><span className="employee-details"><strong>{employee.name}</strong><small>{employee.role || t(locale, "role")}</small><small className="employee-status">{statusIcon(employee.status)}{employee.status === "available" ? t(locale, "available") : employee.status === "on_break" ? t(locale, "onBreak") : employee.status === "occupied" ? t(locale, "occupied") : employee.status}</small></span><span className="employee-actions">{employee.dispatchEnabled && <Radio size={15} className="dispatch-icon" />}{employee.source !== selfSource && <><button type="button" className="icon-action" disabled={busy} onClick={() => onCallEmployee(employee)} title={t(locale, "callEmployee")} aria-label={t(locale, "callEmployee")}><Phone size={15} /></button><button type="button" className="icon-action" disabled={busy} onClick={() => onContactEmployee(employee)} title={t(locale, "contactEmployee")} aria-label={t(locale, "contactEmployee")}><MessageCircle size={15} /></button></>}</span></div>)}</div>{!filteredEmployees.length && <div className="workspace-empty">{t(locale, "noTeamMembers")}</div>}<Pagination page={teamPage} total={filteredEmployees.length} locale={locale} onPage={(page) => changePage("team", page)} /></div>}
  </section>;
}

function Pagination({ page, total, locale, hasMore = false, loading = false, onPage, onNext }: { page: number; total: number; locale: Locale; hasMore?: boolean; loading?: boolean; onPage: (page: number) => void; onNext?: () => void }) {
  const pages = Math.max(1, Math.ceil(total / pageSize));
  if (pages < 2 && !hasMore) return null;
  const current = Math.min(page, pages - 1);
  return <nav className="list-pagination" aria-label={t(locale, "pagination")}><button type="button" disabled={current === 0 || loading} onClick={() => onPage(current - 1)} title={t(locale, "previousPage")} aria-label={t(locale, "previousPage")}><ChevronLeft size={16} /></button><span>{current + 1} / {Math.max(1, pages)}{hasMore ? "+" : ""}</span><button type="button" disabled={loading || (current >= pages - 1 && !hasMore)} onClick={() => current < pages - 1 ? onPage(current + 1) : onNext?.()} title={t(locale, "nextPage")} aria-label={t(locale, "nextPage")}>{loading ? <LoaderCircle className="spinner" size={16} /> : <ChevronRight size={16} />}</button></nav>;
}

function RequestSettingsEditor({ settings, locale, busy, onSave }: { settings: RequestSettings; locale: Locale; busy: boolean; onSave: (settings: Pick<RequestSettings, "label" | "createLabel" | "templateIds" | "fieldSettings" | "numberId" | "navigationOnAccept">) => void }) {
  const [form, setForm] = useState(() => ({ label: settings.label, createLabel: settings.createLabel, templateIds: [...settings.templateIds], numberId: settings.numberId, navigationOnAccept: settings.navigationOnAccept, fieldSettings: Object.fromEntries(settings.templates.map((template) => [template.id, Object.fromEntries(template.fields.map((field) => [field.id, settings.fieldSettings?.[template.id]?.[field.id] ?? { enabled: field.enabled !== false, required: field.required }]))])) }));
  const toggle = (id: string) => setForm((current) => ({ ...current, templateIds: current.templateIds.includes(id) ? current.templateIds.filter((value) => value !== id) : [...current.templateIds, id] }));
  const setField = (templateId: string, fieldId: string, key: "enabled" | "required", value: boolean) => setForm((current) => ({ ...current, fieldSettings: { ...current.fieldSettings, [templateId]: { ...current.fieldSettings[templateId], [fieldId]: { ...current.fieldSettings[templateId][fieldId], [key]: value, ...(key === "enabled" && !value ? { required: false } : {}) } } } }));
  return <div className="request-settings"><label><span>{t(locale, "requestLabel")}</span><input value={form.label} maxLength={80} onChange={(event) => setForm({ ...form, label: event.target.value })} /></label><label><span>{t(locale, "createLabel")}</span><input value={form.createLabel} maxLength={80} onChange={(event) => setForm({ ...form, createLabel: event.target.value })} /></label>{settings.requestNumbers && settings.requestNumbers.length > 0 && <label><span>{t(locale, "phoneNumbers")}</span><select value={form.numberId || ""} onChange={(event) => setForm({ ...form, numberId: event.target.value })}>{settings.requestNumbers.map((number) => <option key={number.id} value={number.id}>{number.label}</option>)}</select></label>}<label><span>{t(locale, "navigation")}</span><select value={form.navigationOnAccept} onChange={(event) => setForm({ ...form, navigationOnAccept: event.target.value as RequestSettings["navigationOnAccept"] })}><option value="disabled">{t(locale, "navigationDisabled")}</option><option value="ask">{t(locale, "navigationAsk")}</option><option value="automatic">{t(locale, "navigationAutomatic")}</option></select></label><strong>{t(locale, "templates")}</strong>{settings.templates.map((template) => <div className="template-settings" key={template.id}><label className="check-row"><input type="checkbox" checked={form.templateIds.includes(template.id)} onChange={() => toggle(template.id)} />{template.name}</label>{form.templateIds.includes(template.id) && template.fields.map((field) => { const state = form.fieldSettings[template.id][field.id]; return <div className="field-setting" key={field.id}><span>{field.label}</span><label><input type="checkbox" checked={state.enabled} onChange={(event) => setField(template.id, field.id, "enabled", event.target.checked)} />{t(locale, "enabled")}</label><label><input type="checkbox" checked={state.required} disabled={!state.enabled} onChange={(event) => setField(template.id, field.id, "required", event.target.checked)} />{t(locale, "required")}</label></div>; })}</div>)}<button type="button" className="save-button" disabled={busy || form.templateIds.length < 1} onClick={() => onSave(form)}>{t(locale, "save")}</button></div>;
}
