import { Check, ChevronRight, History, Inbox, LoaderCircle, Phone, RotateCcw, Send, Trash2 } from "lucide-react";
import { useState } from "react";
import { t, type Locale } from "../lib/i18n";
import type { CitizenRequest, CompanyWorkspace as WorkspaceData, EmployeeStatus, InboxConversation, RequestSettings } from "../types";

type WorkspaceTab = "requests" | "inbox" | "calls";
interface Props {
  data: WorkspaceData | null; locale: Locale; busy: boolean; employeeStatus?: EmployeeStatus; activeRequestId?: number;
  onOpenConversation: (conversation: InboxConversation) => void; onAcceptRequest: (request: CitizenRequest) => void;
  onTransition: (request: CitizenRequest, phaseId: string) => void; onReturn: (request: CitizenRequest) => void;
  onSaveSettings: (settings: Pick<RequestSettings, "label" | "createLabel" | "templateIds" | "phaseIds" | "fieldSettings" | "numberId" | "navigationOnAccept">) => void;
  onDeleteRequest: (request: CitizenRequest) => void; onDeleteConversation: (conversation: InboxConversation) => void;
  isLeader: boolean;
  canDelete: boolean;
}

export function CompanyWorkspace({ data, locale, busy, employeeStatus, activeRequestId, onOpenConversation, onAcceptRequest, onTransition, onReturn, onSaveSettings, onDeleteRequest, onDeleteConversation, isLeader, canDelete }: Props) {
  const [tab, setTab] = useState<WorkspaceTab>("requests"); const [settingsOpen, setSettingsOpen] = useState(false);
  const [selectedInbox, setSelectedInbox] = useState<string>("all");
  const canAcceptRequests = employeeStatus === "available" && !activeRequestId;
  if (!data) return <section className="workspace loading"><LoaderCircle className="spinner" size={22} /></section>;
  return <section className="workspace"><div className="workspace-tabs"><button type="button" className={tab === "requests" ? "active" : ""} onClick={() => setTab("requests")} title={t(locale, "requests")}><Send size={17} /><i>{data.requests.filter((request) => request.status === "pending" || request.status === "returned").length}</i></button><button type="button" className={tab === "inbox" ? "active" : ""} onClick={() => setTab("inbox")} title={t(locale, "inbox")}><Inbox size={17} /><i>{data.conversations.reduce((sum, item) => sum + Number(item.unreadCount || 0), 0)}</i></button><button type="button" className={tab === "calls" ? "active" : ""} onClick={() => setTab("calls")} title={t(locale, "companyCalls")}><History size={17} /></button></div>
    {tab === "requests" && <div className="workspace-list"><header><strong>{data.requestSettings.label}</strong>{isLeader && <button type="button" onClick={() => setSettingsOpen((value) => !value)}>{t(locale, "configure")}</button>}</header>{settingsOpen && <RequestSettingsEditor settings={data.requestSettings} locale={locale} busy={busy} onSave={(settings) => { onSaveSettings(settings); setSettingsOpen(false); }} />}{data.requests.map((request) => { const own = request.id === activeRequestId; const phases = request.phases || data.requestSettings.phases; const current = phases.findIndex((phase) => phase.id === (request.phaseId || request.phase_id)); const next = phases[current + 1]; return <article className="work-row" key={request.id}><span className={`work-state ${request.status}`}><Send size={16} /></span><div><strong>{request.requestLabel || request.request_label || request.templateId || request.template_id}</strong><small>{request.companyName ? `${request.companyName} · ` : ""}{Object.values(request.payload || {}).filter(Boolean).slice(0, 2).join(" · ")}</small><em>{request.status} · {request.phaseId || request.phase_id || t(locale, "waiting")}</em></div><span className="row-actions">{(request.status === "pending" || request.status === "returned") && <button type="button" disabled={busy || !canAcceptRequests} onClick={() => onAcceptRequest(request)} title={t(locale, "accept")}><Check size={16} /></button>}{own && next && <button type="button" disabled={busy} onClick={() => onTransition(request, next.id)} title={next.name}><ChevronRight size={17} /></button>}{own && <button type="button" disabled={busy} onClick={() => onReturn(request)} title={t(locale, "returnRequest")}><RotateCcw size={16} /></button>}{canDelete && request.companyId === data.companyId && <button type="button" className="danger" disabled={busy} onClick={() => onDeleteRequest(request)} title={t(locale, "deleteRequest")}><Trash2 size={16} /></button>}</span></article>; })}{!data.requests.length && <div className="workspace-empty">{t(locale, "noRequests")}</div>}</div>}
    {tab === "inbox" && <div className="workspace-list"><div className="inbox-number-tabs"><button type="button" className={selectedInbox === "all" ? "active" : ""} onClick={() => setSelectedInbox("all")}><Inbox size={15} />{t(locale, "allInboxes")}</button>{data.numberSubscriptions?.filter((number) => number.enabled && number.inboxEnabled && number.authorized).map((number) => <button type="button" className={selectedInbox === number.numberId ? "active" : ""} key={number.numberId} onClick={() => setSelectedInbox(number.numberId)}><Inbox size={15} />{number.label}<i>{data.conversations.filter((item) => item.numberId === number.numberId).reduce((sum, item) => sum + Number(item.unreadCount || 0), 0)}</i></button>)}</div>{data.conversations.filter((conversation) => selectedInbox === "all" || conversation.numberId === selectedInbox).map((conversation) => <article className="conversation-row" key={conversation.id}><button type="button" className="conversation-open" onClick={() => onOpenConversation(conversation)}><span><Inbox size={17} /></span><div><strong>{conversation.externalNumber}</strong><small>{conversation.numberLabel} · {conversation.lastMessage}</small></div>{Number(conversation.unreadCount) > 0 && <i>{conversation.unreadCount}</i>}</button>{canDelete && <button type="button" className="conversation-delete" disabled={busy} onClick={() => onDeleteConversation(conversation)} title={t(locale, "deleteConversation")}><Trash2 size={16} /></button>}</article>)}{!data.conversations.filter((conversation) => selectedInbox === "all" || conversation.numberId === selectedInbox).length && <div className="workspace-empty">{t(locale, "noMessages")}</div>}</div>}
    {tab === "calls" && <div className="workspace-list">{data.calls.map((call) => <article className="work-row" key={call.id}><span className="work-state call"><Phone size={16} /></span><div><strong>{call.callerNumber || t(locale, "unknownCaller")}</strong><small>{call.numberId}</small><em>{call.status} · {new Date(call.created_at).toLocaleDateString(locale)}</em></div></article>)}{!data.calls.length && <div className="workspace-empty">{t(locale, "noCalls")}</div>}</div>}
  </section>;
}

function RequestSettingsEditor({ settings, locale, busy, onSave }: { settings: RequestSettings; locale: Locale; busy: boolean; onSave: (settings: Pick<RequestSettings, "label" | "createLabel" | "templateIds" | "phaseIds" | "fieldSettings" | "numberId" | "navigationOnAccept">) => void }) {
  const [form, setForm] = useState(() => ({ label: settings.label, createLabel: settings.createLabel, templateIds: [...settings.templateIds], phaseIds: [...settings.phaseIds], numberId: settings.numberId, navigationOnAccept: settings.navigationOnAccept, fieldSettings: Object.fromEntries(settings.templates.map((template) => [template.id, Object.fromEntries(template.fields.map((field) => [field.id, settings.fieldSettings?.[template.id]?.[field.id] ?? { enabled: field.enabled !== false, required: field.required }]))])) }));
  const toggle = (key: "templateIds" | "phaseIds", id: string) => setForm((current) => ({ ...current, [key]: current[key].includes(id) ? current[key].filter((value) => value !== id) : [...current[key], id] }));
  const setField = (templateId: string, fieldId: string, key: "enabled" | "required", value: boolean) => setForm((current) => ({ ...current, fieldSettings: { ...current.fieldSettings, [templateId]: { ...current.fieldSettings[templateId], [fieldId]: { ...current.fieldSettings[templateId][fieldId], [key]: value, ...(key === "enabled" && !value ? { required: false } : {}) } } } }));
  return <div className="request-settings"><label><span>{t(locale, "requestLabel")}</span><input value={form.label} maxLength={80} onChange={(event) => setForm({ ...form, label: event.target.value })} /></label><label><span>{t(locale, "createLabel")}</span><input value={form.createLabel} maxLength={80} onChange={(event) => setForm({ ...form, createLabel: event.target.value })} /></label>{settings.requestNumbers && settings.requestNumbers.length > 0 && <label><span>{t(locale, "phoneNumbers")}</span><select value={form.numberId || ""} onChange={(event) => setForm({ ...form, numberId: event.target.value })}>{settings.requestNumbers.map((number) => <option key={number.id} value={number.id}>{number.label}</option>)}</select></label>}<label><span>{t(locale, "navigation")}</span><select value={form.navigationOnAccept} onChange={(event) => setForm({ ...form, navigationOnAccept: event.target.value as RequestSettings["navigationOnAccept"] })}><option value="disabled">{t(locale, "navigationDisabled")}</option><option value="ask">{t(locale, "navigationAsk")}</option><option value="automatic">{t(locale, "navigationAutomatic")}</option></select></label><strong>{t(locale, "templates")}</strong>{settings.templates.map((template) => <div className={`template-settings ${template.kind}`} key={template.id}><span className="template-kind">{t(locale, template.kind === "general" ? "generalRequests" : "specialRequests")}</span><label className="check-row"><input type="checkbox" checked={form.templateIds.includes(template.id)} onChange={() => toggle("templateIds", template.id)} />{template.name}</label>{form.templateIds.includes(template.id) && template.fields.map((field) => { const state = form.fieldSettings[template.id][field.id]; return <div className="field-setting" key={field.id}><span>{field.label}</span><label><input type="checkbox" checked={state.enabled} onChange={(event) => setField(template.id, field.id, "enabled", event.target.checked)} />{t(locale, "enabled")}</label><label><input type="checkbox" checked={state.required} disabled={!state.enabled || field.type === "phone"} onChange={(event) => setField(template.id, field.id, "required", event.target.checked)} />{t(locale, "required")}</label></div>; })}</div>)}<strong>{t(locale, "phases")}</strong>{(settings.availablePhases || settings.phases).map((phase) => <label className="check-row" key={phase.id}><input type="checkbox" checked={form.phaseIds.includes(phase.id)} onChange={() => toggle("phaseIds", phase.id)} />{phase.name}</label>)}<button type="button" className="save-button" disabled={busy || form.templateIds.length < 1 || form.phaseIds.length < 2} onClick={() => onSave(form)}>{t(locale, "save")}</button></div>;
}
