import { ArrowLeft, Image, ImagePlus, LoaderCircle, MapPin, Send, Smile, SmilePlus, Trash2, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { fetchNui } from "../lib/api";
import { subscribeToNui } from "../lib/events";
import { t, type Locale } from "../lib/i18n";
import { openFullscreenMedia, openMediaPicker } from "../lib/phoneComponents";
import type { AppMessage, ConversationData, InboxConversation, InboxMessage, MessageReaction, MessageReactionUpdate } from "../types";
import { EmojiPicker } from "./EmojiPicker";

interface Props {
  conversation: InboxConversation; locale: Locale; citizen: boolean; busy: boolean;
  onClose: () => void; onSend: (conversationId: number, body: string, attachments: string[]) => Promise<InboxMessage | null>;
  onLocation: () => Promise<InboxMessage | null>; onReact: (messageId: number, emoji: string) => Promise<MessageReaction[] | null>;
  canDelete: boolean; onDelete: (messageId: number) => Promise<boolean>;
}
const messageTime = (message: InboxMessage, locale: Locale) => { const timestamp = message.created_at || message.createdAt; return timestamp ? new Date(timestamp).toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" }) : ""; };
export function ConversationView({ conversation, locale, citizen, busy, onClose, onSend, onLocation, onReact, canDelete, onDelete }: Props) {
  const [data, setData] = useState<ConversationData | null>(null); const [body, setBody] = useState(""); const [attachments, setAttachments] = useState<string[]>([]); const [emojiOpen, setEmojiOpen] = useState(false); const [reactionFor, setReactionFor] = useState<number | null>(null); const end = useRef<HTMLDivElement>(null);
  useEffect(() => { let active = true; void fetchNui<ConversationData>("getConversationMessages", { conversationId: conversation.id, citizen, limit: 50 }).then((response) => { if (active && response.success) setData({ ...response.data, messages: [...response.data.messages].reverse() }); }); return () => { active = false; }; }, [conversation.id, citizen]);
  useEffect(() => { end.current?.scrollIntoView(); }, [data?.messages.length]);
  useEffect(() => subscribeToNui((message: AppMessage) => { if (message.type === "inbox.message.deleted") { const update = message.payload as { messageId: number; conversationId: number }; if (update.conversationId === conversation.id) setData((current) => current ? { ...current, messages: current.messages.filter((item) => item.id !== update.messageId) } : current); return; } if (message.type !== "inbox.reaction") return; const update = message.payload as MessageReactionUpdate; if (update.conversationId !== conversation.id) return; setData((current) => current ? { ...current, messages: current.messages.map((item) => { if (item.id !== update.messageId) return item; const reactions = update.reactions.map((reaction) => ({ ...reaction, mine: item.reactions?.some((currentReaction) => currentReaction.emoji === reaction.emoji && currentReaction.mine) === true })); return { ...item, reactions }; }) } : current); }), [conversation.id]);
  const addMedia = () => openMediaPicker((selected) => setAttachments((current) => [...new Set([...current, ...selected])].slice(0, 4)));
  const send = async () => { const sent = await onSend(conversation.id, body.trim(), attachments); if (sent) { setData((current) => current ? { ...current, messages: [...current.messages, sent] } : current); setBody(""); setAttachments([]); setEmojiOpen(false); } };
  const react = async (messageId: number, emoji: string) => { const reactions = await onReact(messageId, emoji); if (reactions) setData((current) => current ? { ...current, messages: current.messages.map((message) => message.id === messageId ? { ...message, reactions } : message) } : current); setReactionFor(null); };
  const removeMessage = async (messageId: number) => { if (await onDelete(messageId)) setData((current) => current ? { ...current, messages: current.messages.filter((message) => message.id !== messageId) } : current); };
  return <main className="conversation-view"><header><button type="button" className="icon-action" onClick={onClose} aria-label={t(locale, "back")}><ArrowLeft size={18} /></button><div><strong>{citizen ? conversation.companyName : conversation.externalNumber}</strong><small>{conversation.numberLabel}</small></div></header>
    <div className="message-stream">{!data && <LoaderCircle className="spinner" size={20} />}{data?.messages.map((message) => <article key={message.id} className={`message-bubble ${message.senderType === (citizen ? "citizen" : "employee") ? "own" : ""}`}>{message.body && <p>{message.body}</p>}{message.attachments?.map((url, index) => <button type="button" className="message-media" onClick={() => openFullscreenMedia(url)} key={url}><Image size={13} />{t(locale, "media")} {index + 1}</button>)}{message.coords && <span><MapPin size={13} />{message.coords.x.toFixed(1)}, {message.coords.y.toFixed(1)}</span>}<time>{messageTime(message, locale)}</time><div className="message-reactions">{message.reactions?.map((reaction) => <button type="button" className={reaction.mine ? "mine" : ""} key={reaction.emoji} onClick={() => void react(message.id, reaction.emoji)}>{reaction.emoji}<i>{reaction.count}</i></button>)}<button type="button" className="reaction-add" onClick={() => setReactionFor((current) => current === message.id ? null : message.id)} aria-label={t(locale, "react")}><SmilePlus size={13} /></button>{canDelete && <button type="button" className="message-delete" disabled={busy} onClick={() => { if (window.confirm(`${t(locale, "deleteMessage")}?`)) void removeMessage(message.id); }} aria-label={t(locale, "deleteMessage")} title={t(locale, "deleteMessage")}><Trash2 size={13} /></button>}</div>{reactionFor === message.id && <EmojiPicker label={t(locale, "reactions")} onSelect={(emoji) => void react(message.id, emoji)} />}</article>)}<div ref={end} /></div>
    <div className="message-compose">{attachments.length > 0 && <div className="selected-media">{attachments.map((url, index) => <span key={url}><ImagePlus size={12} />{index + 1}<button type="button" onClick={() => setAttachments((current) => current.filter((item) => item !== url))} aria-label={t(locale, "removeAttachment")}><X size={11} /></button></span>)}</div>}{emojiOpen && <EmojiPicker label={t(locale, "emojis")} onSelect={(emoji) => setBody((current) => `${current}${emoji}`)} />}<div><button type="button" className="location-send" onClick={() => void onLocation().then((sent) => { if (sent) setData((current) => current ? { ...current, messages: [...current.messages, sent] } : current); })} disabled={busy} aria-label={t(locale, "sendLocation")}><MapPin size={17} /></button><button type="button" className="compose-secondary" onClick={addMedia} disabled={busy || attachments.length >= 4} aria-label={t(locale, "chooseMedia")}><ImagePlus size={17} /></button><button type="button" className={`compose-secondary ${emojiOpen ? "active" : ""}`} onClick={() => setEmojiOpen((current) => !current)} aria-label={t(locale, "emojis")}><Smile size={17} /></button><textarea rows={1} maxLength={2000} value={body} onChange={(event) => setBody(event.target.value)} placeholder={t(locale, "message")} /><button type="button" onClick={() => void send()} disabled={busy || (!body.trim() && attachments.length === 0)} aria-label={t(locale, "send")}><Send size={17} /></button></div></div>
  </main>;
}
